service:
    uri: tcp://*:5555
    deserialize_func: !!python/name:msgpackio.loads
    serialize_func: !!python/name:msgpackio.dumps
    data: {'original': !!python/object/apply:pandas.read_csv [/home/ddorroh/workspace/tensorflow/Tagged.GridImageMetrics.600.csv]}
#    data: {'original': !!python/object/apply:pandas.read_csv [/home/ddorroh/workspace/tensorflow/3BData.csv]}
    